### ISSUE TITLE
Fixed bandplan hoplists and starting from zero

### ISSUE THREAD

**Issue by Bwooce** [mkuyper/basicmac#13]
My understanding is a little weak here, but I noticed that every time I reset the LMIC stack on AU915 (fixed bandplan) I get the same frequency for the first packet. That led me down a rabbit-hole. 

Some questions:
1. [This seems to be where](https://github.com/mkuyper/basicmac/blob/982b514120d5c919fbbdc72215eb25726fa36936/lmic/lmic.c#L1201) the first packet is special-cased and the comment implies it's intentional. Do you know why?
2. The hoplist randomisation [uses a PRNG algorithm](https://github.com/mkuyper/basicmac/blob/982b514120d5c919fbbdc72215eb25726fa36936/lmic/lmic.c#L1169), but ignores the existing source of RNG data (which can be hardware seeded). Changing the hoplist to use the getRndU1 (note: should rename this too) works and simplifies the code. Actually I could use getRndU2 there, since it seems to be constructing 16bits (in a 32 bit int? I need to re-read that to see why)
3. The [DYN txChan ](https://github.com/mkuyper/basicmac/blob/982b514120d5c919fbbdc72215eb25726fa36936/lmic/lmic.c#L1096 )also seem to start at the same place every time, so maybe there is a reason? Not sure if this is actually only on Join, but there's the odd place in BasicMac that sets the txChan to zero rather than a random one.

I will send a PR but want to confirm this is not intentional first, and maybe dig into the DYN case a little more.

**Comment by mkuyper** [comment]
1) Yes, this is intentional; although maybe not ideal. Since full 64+8 channel gateways are quite rare, most networks in fixed-channel regions employ either an 8+1 or 16+2 channel plan, where channels 0-7+64 seems to be the most popular choice -- as is the case for deployments of the TrackCentral network server. That special treatment ensures that the first frequency is from that first block of 8 channels, in hopes of a quick join.

2) This is intentional as well. Using a PRNG seeded by the device EUI makes the hoplist deterministic per device. This has proved to be very valuable when diagnosing network level issues in active deployments. For example, if packet loss is detected on the network side by observing gaps in FCntUp, the channel on which the loss occurred can be inferred.

3) For dynamic channel plans, the above does not really apply. That's why the XXX comment indicates that the nextTx() mechanism should really be used -- for nextJoinState too. As it is right now, the join sequence in dynamic channel plan regions behaves completely differently than regular operation.


I don't have strong feelings about 1) -- it works well for me, but I am biased. I would be fine with not prioritizing the first channel block if there's a good reason no to. However, I would be very hesitant to change 2) for the reason listed above. Of course, 3) should be fixed sooner or later.

**Comment by Bwooce** [comment]
Thanks for the explanation @mkuyper, makes sense. I'm perhaps over optimising the startup in any case, it's just that I was resetting the stack for every packet (!) as I switched band plans. Now I've stopped it's not really noticable and I'm regretting opening the issue, but again appreciate understanding.

1. Agreed this is common, and the LoRAWAN standard is a little overzealous here although it sounds like TTN might be about to expand to >8 channels. Should this always be channel 1 in block 1 (e.g. index 0), or would rndU1() mod 8 be enough to (a) make it stay within the block and (b) not be deterministic. [some other LMICs use mod 3 for DYN](https://github.com/mcci-catena/arduino-lmic/blob/100037d2e1a69b7690e333076e94bd83f1c90715/src/lmic/lmic_eu_like.c#L131) or mod 64 for FIXed. Which is totally correct in LoRaWAN terms, but crappy for getting a connection quickly as discussed above.
2. Agreed. Sounds good to keep.
3. I imagine it's not as easy as calling nextTx(), but I don't understand why. I will study, while I'm here, and see if I can improve the world a little.
